on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 12 * *"

name: R-CMD-check

jobs:
  check_package:
    strategy:
      fail-fast: false
      matrix:
        include:
          - install_mhcnuggets: "true" 
          - install_mhcnuggets: "false"

    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install libcurl4-openssl-dev
        run: sudo apt install -qq libcurl4-openssl-dev

      - name: Install libgit2-dev
        run: sudo apt install -qq libgit2-dev

      - name: Install libharfbuzz-dev libfribidi-dev
        run: sudo apt install -qq libharfbuzz-dev libfribidi-dev

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "semver"))
          remotes::install_github("richelbilderbeek/plinkr")
          remotes::install_github("richelbilderbeek/ormr")
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_cran("covr")
          remotes::install_cran("lintr")
          remotes::install_github("MangoTheCat/goodpractice")
          remotes::install_github("richelbilderbeek/mhcnuggetsr")
        shell: Rscript {0}

      - name: Install mhcnuggetsrinstall
        env:
          INSTALL_MHCNUGGETS: ${{ matrix.install_mhcnuggets }}
        run: if [[ "$INSTALL_MHCNUGGETS" == true ]]; then Rscript -e 'remotes::install_github("richelbilderbeek/mhcnuggetsrinstall")'; fi

      - name: Show 'mhcnuggetsr::is_mhcnuggets_installed'
        env:
          INSTALL_MHCNUGGETS: ${{ matrix.install_mhcnuggets }}
        run: if [[ "$INSTALL_MHCNUGGETS" == true ]]; then Rscript -e 'mhcnuggetsr::is_mhcnuggets_installed'; fi

      - name: Show 'mhcnuggetsrinstall::install_mhcnuggets'
        env:
          INSTALL_MHCNUGGETS: ${{ matrix.install_mhcnuggets }}
        run: if [[ "$INSTALL_MHCNUGGETS" == true ]]; then Rscript -e 'mhcnuggetsrinstall::install_mhcnuggets'; fi

      - name: Install MHCnuggets
        env:
          INSTALL_MHCNUGGETS: ${{ matrix.install_mhcnuggets }}
        run: if [[ "$INSTALL_MHCNUGGETS" == true ]]; then Rscript -e 'mhcnuggetsrinstall::install_mhcnuggets()'; fi

      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}

      - name: Test coverage
        run: if [[ "$INSTALL_MHCNUGGETS" == true ]]; then Rscript -e 'covr::codecov()'; fi

      - name: Lint
        run: if [[ "$INSTALL_MHCNUGGETS" == false ]]; then Rscript -e 'lintr::lint_package()'; fi

